version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sample-rest"
s3_bucket = "rahul455"
s3_prefix = "sample-rest"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
